import type { HarnessCatalogSnapshot } from '@/harness-core/model';
import { isCatalogHashCurrent } from '@/harness-core/catalogHash';
import { harnessCatalogSnapshotSchema } from '@/harness-core/serialization';

function identifier(value: string): string {
  const words = value.replace(/[^A-Za-z0-9]+/g, ' ').trim().split(/\s+/);
  const joined = words.map((word) => `${word.slice(0, 1).toUpperCase()}${word.slice(1)}`).join('');
  return /^[A-Za-z_$]/.test(joined) ? joined : `Family${joined}`;
}

function cavityKey(familyId: string, cavityId: string): string {
  const prefix = `${familyId}.`;
  return cavityId.startsWith(prefix) ? cavityId.slice(prefix.length) : cavityId;
}

export function generateConnectorDeclarations(snapshot: HarnessCatalogSnapshot): string {
  harnessCatalogSnapshotSchema.parse(snapshot);
  if (!isCatalogHashCurrent(snapshot)) {
    throw new Error(`Cannot generate connector declarations from stale catalog snapshot ${snapshot.snapshotId}.`);
  }

  const lines = [
    '// Generated by TOMINAL-CORE-X1. Do not edit by hand.',
    `// Catalog snapshot: ${snapshot.snapshotId}`,
    `// Catalog hash: ${snapshot.snapshotHash}`,
    "import { defineConnectorFamily } from '@/harness-authoring';",
    "import { catalogPartId, signalRoleId } from '@/harness-core';",
    ''
  ];

  for (const family of [...snapshot.connectorFamilies].sort((left, right) => left.id.localeCompare(right.id))) {
    lines.push(`export const ${identifier(family.name)}Family = defineConnectorFamily({`);
    lines.push(`  id: ${JSON.stringify(family.id)},`);
    lines.push(`  name: ${JSON.stringify(family.name)},`);
    if (family.manufacturer) lines.push(`  manufacturer: ${JSON.stringify(family.manufacturer)},`);
    if (family.housingPartId) lines.push(`  housingPartId: catalogPartId(${JSON.stringify(family.housingPartId)}),`);
    if (family.housingPartNumber) lines.push(`  housingPartNumber: ${JSON.stringify(family.housingPartNumber)},`);
    lines.push('  cavities: {');
    for (const cavity of [...family.cavities].sort((left, right) => left.id.localeCompare(right.id))) {
      lines.push(`    ${JSON.stringify(cavityKey(family.id, cavity.id))}: {`);
      lines.push(`      label: ${JSON.stringify(cavity.label)},`);
      if (cavity.required) lines.push('      required: true,');
      if (cavity.requiredRole) lines.push(`      requiredRole: signalRoleId(${JSON.stringify(cavity.requiredRole)}),`);
      lines.push(
        `      allowedTerminalIds: [${cavity.allowedTerminalIds
          .map((part) => `catalogPartId(${JSON.stringify(part)})`)
          .join(', ')}],`
      );
      if (cavity.allowedSealIds) {
        lines.push(
          `      allowedSealIds: [${cavity.allowedSealIds
            .map((part) => `catalogPartId(${JSON.stringify(part)})`)
            .join(', ')}],`
        );
      }
      if (cavity.allowedPlugIds) {
        lines.push(
          `      allowedPlugIds: [${cavity.allowedPlugIds
            .map((part) => `catalogPartId(${JSON.stringify(part)})`)
            .join(', ')}],`
        );
      }
      lines.push('    },');
    }
    lines.push('  },');
    lines.push('} as const);', '');
  }

  return lines.join('\n');
}
