// Generated by TOMINAL-CORE-X1. Do not edit by hand.
// Catalog snapshot: controller-chassis-demo-v1
// Catalog hash: fnv1a32:e1e1b7f1
import { defineConnectorFamily } from '@/harness-authoring';
import { catalogPartId, signalRoleId } from '@/harness-core';

export const Motor3Family = defineConnectorFamily({
  id: "DEMO_MOTOR_3",
  name: "Motor 3",
  manufacturer: "Tominal Demo Parts",
  housingPartId: catalogPartId("HOUSING_MOTOR_3"),
  housingPartNumber: "DEMO-HOUSING-MOTOR-3",
  cavities: {
    "ENABLE": {
      label: "Enable",
      required: true,
      requiredRole: signalRoleId("MOTOR_ENABLE"),
      allowedTerminalIds: [catalogPartId("TERM_SIGNAL")],
      allowedSealIds: [catalogPartId("SEAL_SIGNAL")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
    "MOTOR_NEG": {
      label: "Motor -",
      required: true,
      requiredRole: signalRoleId("MOTOR_NEG"),
      allowedTerminalIds: [catalogPartId("TERM_POWER")],
      allowedSealIds: [catalogPartId("SEAL_POWER")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
    "MOTOR_POS": {
      label: "Motor +",
      required: true,
      requiredRole: signalRoleId("MOTOR_POS"),
      allowedTerminalIds: [catalogPartId("TERM_POWER")],
      allowedSealIds: [catalogPartId("SEAL_POWER")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
  },
} as const);

export const Power3Family = defineConnectorFamily({
  id: "DEMO_POWER_3",
  name: "Power 3",
  manufacturer: "Tominal Demo Parts",
  housingPartId: catalogPartId("HOUSING_POWER_3"),
  housingPartNumber: "DEMO-HOUSING-POWER-3",
  cavities: {
    "CHASSIS_GROUND": {
      label: "Chassis ground",
      required: true,
      requiredRole: signalRoleId("CHASSIS_GROUND"),
      allowedTerminalIds: [catalogPartId("TERM_GROUND")],
      allowedSealIds: [catalogPartId("SEAL_POWER")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
    "VIN_NEG": {
      label: "DC input -",
      required: true,
      requiredRole: signalRoleId("VIN_NEG"),
      allowedTerminalIds: [catalogPartId("TERM_POWER")],
      allowedSealIds: [catalogPartId("SEAL_POWER")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
    "VIN_POS": {
      label: "DC input +",
      required: true,
      requiredRole: signalRoleId("VIN_POS"),
      allowedTerminalIds: [catalogPartId("TERM_POWER")],
      allowedSealIds: [catalogPartId("SEAL_POWER")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
  },
} as const);

export const Sensor3Family = defineConnectorFamily({
  id: "DEMO_SENSOR_3",
  name: "Sensor 3",
  manufacturer: "Tominal Demo Parts",
  housingPartId: catalogPartId("HOUSING_SENSOR_3"),
  housingPartNumber: "DEMO-HOUSING-SENSOR-3",
  cavities: {
    "ENCODER_A": {
      label: "Encoder A",
      required: true,
      requiredRole: signalRoleId("ENCODER_A"),
      allowedTerminalIds: [catalogPartId("TERM_SIGNAL")],
      allowedSealIds: [catalogPartId("SEAL_SIGNAL")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
    "ENCODER_B": {
      label: "Encoder B",
      required: true,
      requiredRole: signalRoleId("ENCODER_B"),
      allowedTerminalIds: [catalogPartId("TERM_SIGNAL")],
      allowedSealIds: [catalogPartId("SEAL_SIGNAL")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
    "TEMPERATURE": {
      label: "Temperature",
      required: true,
      requiredRole: signalRoleId("TEMPERATURE"),
      allowedTerminalIds: [catalogPartId("TERM_SIGNAL")],
      allowedSealIds: [catalogPartId("SEAL_SIGNAL")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
  },
} as const);

export const Service3Family = defineConnectorFamily({
  id: "DEMO_SERVICE_3",
  name: "Service 3",
  manufacturer: "Tominal Demo Parts",
  housingPartId: catalogPartId("HOUSING_SERVICE_3"),
  housingPartNumber: "DEMO-HOUSING-SERVICE-3",
  cavities: {
    "GROUND_RESERVED": {
      label: "Reserved ground",
      allowedTerminalIds: [catalogPartId("TERM_SIGNAL")],
      allowedSealIds: [catalogPartId("SEAL_SIGNAL")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
    "RX": {
      label: "Service RX",
      required: true,
      requiredRole: signalRoleId("SERVICE_RX"),
      allowedTerminalIds: [catalogPartId("TERM_SIGNAL")],
      allowedSealIds: [catalogPartId("SEAL_SIGNAL")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
    "TX": {
      label: "Service TX",
      required: true,
      requiredRole: signalRoleId("SERVICE_TX"),
      allowedTerminalIds: [catalogPartId("TERM_SIGNAL")],
      allowedSealIds: [catalogPartId("SEAL_SIGNAL")],
      allowedPlugIds: [catalogPartId("PLUG_DEMO")],
    },
  },
} as const);
